# Generated by Django 3.1.6 on 2021-02-15 05:47

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20210215_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='body',
            field=wagtail.core.fields.RichTextField(max_length=1000),
        ),
    ]
