# Generated by Django 3.1.6 on 2021-02-15 06:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('cms', '0003_auto_20210215_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock(icon='doc_full', label='Rich Text', required=False)), ('html', wagtail.core.blocks.RawHTMLBlock(icon='code', label='Raw HTML', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image', required=False))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
