# Generated by Django 3.1.6 on 2021-02-17 00:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('cms', '0005_contentsimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyColumnPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('two_column', wagtail.core.blocks.StreamBlock([('column_1_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())])), ('column_1', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())]))], group='Columns', template='home/blocks/two_column_block.html'))], label='two column', required=False)), ('three_column', wagtail.core.blocks.StreamBlock([('column_1_1_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())])), ('column_1', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())])), ('column_2', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())]))], group='Columns', template='home/blocks/three_column_block.html'))], label='three column', required=False))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
