# Generated by Django 3.1.6 on 2021-02-19 01:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_mycolumnpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycolumnpage',
            name='body',
            field=wagtail.core.fields.StreamField([('two_columns', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())])), ('column_1', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())])), ('column_2', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())]))], group='Columns', template='cms/blocks/three_column_block.html')), ('three_columns', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())])), ('column_1', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())]))], group='Columns', template='cms/blocks/two_column_block.html'))]),
        ),
    ]
