# Generated by Django 3.1.6 on 2021-02-20 11:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('cms', '0008_auto_20210219_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyColumnPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cms.mycolumnpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_mycolumnpagetag_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contentspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ContentsImages',
        ),
        migrations.DeleteModel(
            name='ContentsPage',
        ),
        migrations.AddField(
            model_name='mycolumnpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cms.MyColumnPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
