# Generated by Django 3.1.6 on 2021-02-22 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('cms', '0010_auto_20210222_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='toppagegalleryimage',
            name='page',
        ),
        migrations.DeleteModel(
            name='TopPage',
        ),
        migrations.DeleteModel(
            name='TopPageGalleryImage',
        ),
    ]
