# Generated by Django 3.1.6 on 2021-02-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20210222_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycolumnpage',
            name='post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
