# Generated by Django 3.1.6 on 2021-02-23 06:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('cms', '0012_mycolumnpage_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycolumnpage',
            name='post_date',
            field=models.DateField(auto_now_add=True, default='2021-01-01'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MyColumnPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='cms.mycolumnpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
