# Generated by Django 3.1.6 on 2021-02-17 00:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0010_auto_20210216_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycolumnpage',
            name='body',
            field=wagtail.core.fields.StreamField([('two_column', wagtail.core.blocks.StreamBlock([('column_1_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())])), ('column_1', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())]))], group='Columns', template='home/blocks/two_column_block.html'))], label='two column', required=False)), ('three_column', wagtail.core.blocks.StreamBlock([('column_1_1_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())])), ('column_1', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())])), ('column_2', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext', wagtail.core.blocks.RichTextBlock())]))], group='Columns', template='home/blocks/three_column_block.html'))], label='three column', required=False))]),
        ),
        migrations.DeleteModel(
            name='ThreeColumnPage',
        ),
    ]
