# Generated by Django 3.1.6 on 2021-02-17 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0011_auto_20210217_0025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyColumnPage',
        ),
    ]
